"""add_workspaces_and_members_tables

Revision ID: 167323b801ec
Revises: 5bad02e9bf55
Create Date: 2026-06-28 00:25:42.018015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167323b801ec'
down_revision: Union[str, Sequence[str], None] = '5bad02e9bf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_boards_workspace_id'), 'boards', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'boards', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('requests', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_requests_workspace_id'), 'requests', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'requests', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_index(op.f('ix_requests_workspace_id'), table_name='requests')
    op.drop_column('requests', 'workspace_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_column('notifications', 'workspace_id')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_index(op.f('ix_boards_workspace_id'), table_name='boards')
    op.drop_column('boards', 'workspace_id')
    # ### end Alembic commands ###
