"""baseline

Revision ID: c9466707a980
Revises: 
Create Date: 2026-06-19 23:19:32.694214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9466707a980'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('member_username', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_members_id'), 'board_members', ['id'], unique=False)
    op.create_index(op.f('ix_board_members_member_username'), 'board_members', ['member_username'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('owner_username', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('statuses', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('deletion_date', sa.DateTime(), nullable=True),
    sa.Column('is_private', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_id'), 'boards', ['id'], unique=False)
    op.create_index(op.f('ix_boards_owner_username'), 'boards', ['owner_username'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_request_id'), 'comments', ['request_id'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_username', sa.String(length=50), nullable=True),
    sa.Column('receiver_username', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('is_deleted_by_sender', sa.Integer(), nullable=True),
    sa.Column('is_deleted_by_receiver', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_messages_id'), 'direct_messages', ['id'], unique=False)
    op.create_index(op.f('ix_direct_messages_receiver_username'), 'direct_messages', ['receiver_username'], unique=False)
    op.create_index(op.f('ix_direct_messages_sender_username'), 'direct_messages', ['sender_username'], unique=False)
    op.create_table('leave_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leave_date')
    )
    op.create_index(op.f('ix_leave_days_id'), 'leave_days', ['id'], unique=False)
    op.create_table('leave_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('leave_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_records_id'), 'leave_records', ['id'], unique=False)
    op.create_index(op.f('ix_leave_records_leave_date'), 'leave_records', ['leave_date'], unique=False)
    op.create_index(op.f('ix_leave_records_username'), 'leave_records', ['username'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('related_task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_username'), 'notifications', ['user_username'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('requester', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supporting_access', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('owner_username', sa.String(length=50), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('etc', sa.Float(), nullable=True),
    sa.Column('auto_nudge', sa.Boolean(), nullable=True),
    sa.Column('recurring', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_board_id'), 'requests', ['board_id'], unique=False)
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_index(op.f('ix_requests_owner_username'), 'requests', ['owner_username'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('is_done', sa.Integer(), nullable=True),
    sa.Column('assignee', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.create_index(op.f('ix_subtasks_request_id'), 'subtasks', ['request_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('deletion_date', sa.DateTime(), nullable=True),
    sa.Column('is_superadmin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subtasks_request_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_requests_owner_username'), table_name='requests')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_board_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_notifications_user_username'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_leave_records_username'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_leave_date'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_id'), table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index(op.f('ix_leave_days_id'), table_name='leave_days')
    op.drop_table('leave_days')
    op.drop_index(op.f('ix_direct_messages_sender_username'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_receiver_username'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_id'), table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index(op.f('ix_comments_request_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_boards_owner_username'), table_name='boards')
    op.drop_index(op.f('ix_boards_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_board_members_member_username'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_id'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.drop_table('board_members')
    # ### end Alembic commands ###
